using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OmniGenerator.Lib.Interfaces.FieldGenerators
{
    /// <summary>
    /// Defines the interface for all field generators.
    /// </summary>
    internal interface IFieldGenerator
    {
        /// <summary>
        /// Gets the unique name of the field generator.
        /// The name must be unique across all fields in the parameters.
        /// </summary>
        string Name { get; }

        /// <summary>
        /// Gets the last value generated by this field generator.
        /// </summary>
        object LastValue { get; }

        /// <summary>
        /// Generates and returns the next value for this field generator.
        /// </summary>
        /// <returns>
        /// The next generated value as an <see cref="object"/>.
        /// </returns>
        object GenerateNextValue();
    }
}
