<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	
  <ItemGroup>
	<InternalsVisibleTo Include="OmniGenerator.Cli" />
	<InternalsVisibleTo Include="OmniGenerator.Test" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="D20Tek.Spectre.Console.Extensions" Version="1.56.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Quartz" Version="3.18.2" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.18.2" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.2" />
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OmniGenerator.Lib\OmniGenerator.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Nerdbank.GitVersioning" Version="3.10.91" />
  </ItemGroup>

  </Project>
