using Riok.Mapperly.Abstractions;
using OmniGenerator.Lib.Configuration.Fields;
using OmniGenerator.Lib.Generators.Fields;
using OmniGenerator.Lib.Interfaces;
using OmniGenerator.Lib.Interfaces.FieldGenerators;
using OmniGenerator.Lib.Tools;

namespace OmniGenerator.Lib.Mapping
{
    /// <summary>
    /// Mapper for converting field configurations to field generators using Mapperly.
    /// Uses the Factory Pattern to handle polymorphic mappings.
    /// </summary>
    [Mapper]
    internal partial class FieldConfigurationMapper : IFieldMapper
    {
        #region Simple Mappings (Auto-generated by Mapperly)

        internal partial FieldGeneratorRegex Map(FieldConfigurationRegex source);
        internal partial FieldGeneratorConstant Map(FieldConfigurationConstant source);
        internal partial FieldGeneratorNumeric Map(FieldConfigurationNumeric source);
        internal partial FieldGeneratorDate Map(FieldConfigurationDate source);
        internal partial FieldGeneratorIncrement Map(FieldConfigurationIncrement source);
        internal partial FieldGeneratorKeyCalculator Map(FieldConfigurationKeyCalculator source);
        internal partial FieldGeneratorComposite Map(FieldConfigurationComposite source);
        [MapperIgnoreTarget(nameof(FieldGeneratorAggregate.Group))]
        internal partial FieldGeneratorAggregate Map(FieldConfigurationAggregate source);

        #endregion

        #region Custom Mappings

        /// <summary>
        /// Custom mapping for FieldConfigurationWeightedList to FieldGeneratorWeightedList.
        /// Resolves the list from file (if specified) or configuration, then creates the generator.
        /// </summary>
        /// <param name="source">The weighted list configuration.</param>
        /// <returns>The mapped weighted list generator.</returns>
        private FieldGeneratorWeightedList Map(FieldConfigurationWeightedList source)
        {
            // Resolve the list: priority to file if it exists, otherwise use configured list
            var fileLoader = new WeightedValueFileLoader();
            var resolvedList = ListResolver.ResolveList(
                source.List,
                source.ListFilePath,
                fileLoader);

            return new FieldGeneratorWeightedList(source.Name, resolvedList);
        }

        #endregion

        #region Polymorphic Mapping (Factory Method)

        /// <summary>
        /// Maps a field configuration to its corresponding field generator.
        /// This method handles polymorphic mapping using a switch expression.
        /// </summary>
        /// <param name="config">The field configuration to map.</param>
        /// <returns>The corresponding field generator.</returns>
        /// <exception cref="NotSupportedException">Thrown when the configuration type is not supported.</exception>
        IFieldGenerator IFieldMapper.Map(AbstractFieldConfigurationBase config)
        {
            return config switch
            {
                // Simple fields
                FieldConfigurationRegex regex => Map(regex),
                FieldConfigurationConstant constant => Map(constant),
                FieldConfigurationNumeric numeric => Map(numeric),
                FieldConfigurationDate date => Map(date),
                FieldConfigurationIncrement increment => Map(increment),

                // Dependent fields
                FieldConfigurationKeyCalculator key => Map(key),
                FieldConfigurationComposite composite => Map(composite),
                FieldConfigurationAggregate aggregate => Map(aggregate),

                // List fields (custom mapping)
                FieldConfigurationWeightedList weighted => Map(weighted),

                // Unsupported type
                _ => throw new NotSupportedException(
                    $"Configuration type '{config.GetType().Name}' is not supported for mapping.")
            };
        }

        /// <summary>
        /// Maps a list of field configurations to their corresponding field generators.
        /// </summary>
        /// <param name="configs">The list of field configurations to map.</param>
        /// <returns>A list of mapped field generators.</returns>
        List<IFieldGenerator> IFieldMapper.MapList(List<AbstractFieldConfigurationBase> configs)
        {
            if (configs == null || configs.Count == 0)
                return new List<IFieldGenerator>();

            return configs.Select(c => ((IFieldMapper)this).Map(c)).ToList();
        }

        #endregion
    }
}
