<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Services\**" />
	  <EmbeddedResource Remove="Services\**" />
	  <None Remove="Services\**" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\Cmc7.ttf" />
		<None Remove="Resources\Fonts\Cmc7.ttf" />
		<None Remove="Resources\Fonts\OcrbRegular.ttf" />
		<None Remove="Resources\Fonts\CaveatRegular.ttf" />
		<None Remove="Resources\OCRB Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\Fonts\Cmc7.ttf" />
		<EmbeddedResource Include="Resources\Fonts\OcrbRegular.ttf" />
		<EmbeddedResource Include="Resources\Fonts\CaveatRegular.ttf" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="9.0.0" />
		<PackageReference Include="Autofac.Configuration" Version="7.0.0" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
		<PackageReference Include="Barcoder" Version="3.0.0" />
		<PackageReference Include="Barcoder.Renderer.Svg" Version="3.0.0" />
		<PackageReference Include="BenchmarkDotNet.Annotations" Version="0.15.8" />
		<PackageReference Include="DotLiquid" Version="2.3.197" />
		<PackageReference Include="Fare" Version="2.2.1" />
		<PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.10.3" />
		<PackageReference Include="McMaster.NETCore.Plugins" Version="2.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
		<PackageReference Include="Microsoft.ProgramSynthesis.Detection" Version="10.16.5" />
		<PackageReference Include="Riok.Mapperly" Version="4.3.1" />
		<PackageReference Include="Serilog.Extensions.Autofac.DependencyInjection" Version="5.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
		<PackageReference Include="Svg" Version="3.4.7" />
		<PackageReference Include="Roslynator.Analyzers" Version="4.15.0" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Update="Resources\Lists\addresses.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\codes_banques.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\first_names.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\last_names.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\dice.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\dice_pdf.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\zipcodes_cities.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Nerdbank.GitVersioning" Version="3.9.50" />
	</ItemGroup>

</Project>
