<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="OmniGenerator.Cli" />
		<InternalsVisibleTo Include="OmniGenerator.Test" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\Cmc7.ttf" />
		<None Remove="Resources\Fonts\Cmc7.ttf" />
		<None Remove="Resources\Fonts\OcrbRegular.ttf" />
		<None Remove="Resources\OCRB Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\Fonts\Cmc7.ttf" />
		<EmbeddedResource Include="Resources\Fonts\OcrbRegular.ttf" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="8.2.0" />
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="BenchmarkDotNet.Annotations" Version="0.14.0" />
		<PackageReference Include="Fare" Version="2.2.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.1" />
		<PackageReference Include="Microsoft.ProgramSynthesis.Detection" Version="10.4.1" />
		<PackageReference Include="mustache-sharp" Version="1.0.0" />
		<PackageReference Include="Serilog.Extensions.Autofac.DependencyInjection" Version="5.0.0" />
		<PackageReference Include="Svg" Version="3.4.7" />
		<PackageReference Include="System.ComponentModel.Composition" Version="9.0.1" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Update="Resources\Lists\addresses.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\codes_banques.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\first_names.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\last_names.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\dice.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\dice_pdf.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Lists\zipcodes_cities.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Nerdbank.GitVersioning" Version="3.7.115" />
	</ItemGroup>

</Project>
